# Generated by Django 5.0.6 on 2024-07-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('enero - abril', 'enero - abril'), ('mayo -  agosto', 'mayo - agosto'), ('septiembre - diciembre', 'septiembre - diciembre')], max_length=25, verbose_name='Periodo')),
                ('year', models.CharField(default=2024, max_length=4, verbose_name='Año')),
                ('cicle', models.CharField(default='2024 - 2025', max_length=15, verbose_name='Ciclo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=2, verbose_name='Cuatrimestre')),
                ('semester_name', models.CharField(max_length=10, verbose_name='Cuatrimestre en Letra')),
            ],
            options={
                'verbose_name': 'Cuatrimestre',
                'verbose_name_plural': 'Cuatrimestres',
                'ordering': ['id'],
            },
        ),
    ]
