# Generated by Django 5.0.6 on 2024-08-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='cycle',
            field=models.CharField(default='2024 - 2025', max_length=15, verbose_name='Ciclo'),
        ),
    ]
