# Generated by Django 5.0.6 on 2024-06-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('shortname', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('plan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
