# Generated by Django 5.0.6 on 2024-06-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_career_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='level',
            field=models.CharField(choices=[('TSU', 'Tecnico Superior Universitario'), ('Ing', 'Ingenieria'), ('Lic', 'Licenciatura'), ('M', 'Maestria')], max_length=3),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('weekly_hours', models.IntegerField()),
                ('file', models.CharField(max_length=100)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career')),
            ],
        ),
    ]
