# Generated by Django 5.0.6 on 2024-07-04 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_professor_options_alter_student_options_and_more'),
        ('career', '0003_alter_career_level_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AddField(
            model_name='career',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.professor', verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
