# Generated by Django 5.0.6 on 2024-07-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_professor_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Profeso r', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.CharField(max_length=12, verbose_name='Matricula'),
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
    ]
