# Generated by Django 5.0.6 on 2024-07-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_professor_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
